"""empty message

Revision ID: 33b17dbc7dab
Revises: a9c436a02658
Create Date: 2021-05-06 18:55:33.888640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b17dbc7dab'
down_revision = 'a9c436a02658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_url',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url_associate.id'], ),
    sa.PrimaryKeyConstraint('url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_url')
    # ### end Alembic commands ###
