"""empty message

Revision ID: 4b3c410d725f
Revises: 
Create Date: 2021-05-06 16:26:32.971776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3c410d725f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_associate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_associate')
    op.drop_table('bad_url')
    # ### end Alembic commands ###
