"""empty message

Revision ID: 94b6c56835f2
Revises: 33b17dbc7dab
Create Date: 2021-05-06 21:49:58.485309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b6c56835f2'
down_revision = '33b17dbc7dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_associate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('long', sa.String(length=128), nullable=False),
    sa.Column('short', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bad_url',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url_associate.id'], ),
    sa.PrimaryKeyConstraint('url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_url')
    op.drop_table('url_associate')
    # ### end Alembic commands ###
