"""empty message

Revision ID: 97f94407d733
Revises: 382c8a47ba1f
Create Date: 2021-05-06 17:50:26.827010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f94407d733'
down_revision = '382c8a47ba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_url',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url_associate.id'], ),
    sa.PrimaryKeyConstraint('url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_url')
    # ### end Alembic commands ###
