"""empty message

Revision ID: a8274828f7a8
Revises: 97f94407d733
Create Date: 2021-05-06 18:38:33.288463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8274828f7a8'
down_revision = '97f94407d733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_url',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url_associate.id'], ),
    sa.PrimaryKeyConstraint('url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_url')
    # ### end Alembic commands ###
