"""empty message

Revision ID: a9c436a02658
Revises: f4a7f9a4e2c1
Create Date: 2021-05-06 18:53:52.350879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9c436a02658'
down_revision = 'f4a7f9a4e2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bad_url', 'start_datetime')
    op.drop_column('bad_url', 'end_datetime')
    op.drop_column('bad_url', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bad_url', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('bad_url', sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bad_url', sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
