"""empty message

Revision ID: cca8dc7c6fb1
Revises: 4b3c410d725f
Create Date: 2021-05-06 16:41:01.154371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca8dc7c6fb1'
down_revision = '4b3c410d725f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_associate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('long_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_associate')
    # ### end Alembic commands ###
